### ISSUE TITLE
Compilation errors with Delphi 10.2 Tokyo

### ISSUE THREAD

**Issue by andrea-magni** [andrea-magni/MARS#88]
Some packages (MARS.Utils, MARS.mORMot, MARS.JOSE) do not compile with Delphi 10.2 Tokyo or emits many warnings (implicitly imported units).
